[window]
dimensions = { columns = 122, lines = 34 }
padding = { x = 10, y = 10 }
decorations = "none"
opacity = 0.5
blur = true

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular" }
bold = { family = "Hack Nerd Font Mono", style = "Bold" }
size = 13

[env]
TERM = "xterm-256color"  # ✅ Enables both 256-color and TrueColor support

[colors]
primary = { background = "#0f111a", foreground = "#c5cdd9" }

# 16 ANSI Colors
normal = { black = "#1e1e2e", red = "#f7768e", green = "#9ece6a", yellow = "#e0af68",blue = "#7aa2f7", magenta = "#bb9af7", cyan = "#7dcfff", white = "#c0caf5" }

bright = { black = "#3b4261", red = "#f7768e", green = "#9ece6a", yellow = "#e0af68",blue = "#7aa2f7", magenta = "#bb9af7", cyan = "#7dcfff", white = "#a9b1d6" }

# Cursor and selection
cursor = { text = "CellBackground", cursor = "CellForeground" }
selection = { text = "#0f111a", background = "#7dcfff" }
